### ISSUE TITLE
Version 1.1.1 - Server Crash

### ISSUE THREAD

**Issue by JoshMayberry** [cakewhip/ezpas#9]
We have been using version 1.0.4 for minecraft 1.16 on a server.
When we upgraded to version 1.1.1, the server would crash any time someone tried to log on.
Version 1.1.1 works in a single player world, but seems to crash in a multi-player world.

**Comment by cakewhip** [comment]
Please attach a crash log.

**Comment by JoshMayberry** [comment]
I'm so sorry, I had forgotten to attach that.
Here it is.
[crash-2020-08-11_18.33.37-server.txt](https://github.com/cakewhip/ezpas/files/5059792/crash-2020-08-11_18.33.37-server.txt)

**Comment by JoshMayberry** [comment]
It looks like PullerPipeBlockEntity.calculateInsertionPoints got stuck in a recursive loop.

**Comment by JoshMayberry** [comment]
Here are some screen shots of the setup.
I think the issue is not that it is a server, but the existing setup I had with the previous version.

I punched out the things surrounding it and put up some white concrete for better pictures.

![image](https://user-images.githubusercontent.com/11482252/89957030-6aeb3200-dc04-11ea-8793-de63fc821e6d.png)

Items flow from the input chests to the smelter array:
![image](https://user-images.githubusercontent.com/11482252/89957597-d255b180-dc05-11ea-84d0-3dd01ab240b5.png)

Then to storage 1 and storage 2. **Storage 1 has lots of filter pipes connected in a large matrix, which might be an issue** (I did this so I could have more filter slots to put things in the chest, because 1 line of items wasn't enough):
![image](https://user-images.githubusercontent.com/11482252/89957510-9884ab00-dc05-11ea-9a17-ac87f7927dd5.png)

**One place that might be an issue is here, where the output from the smelters is sent back to the main bus:** (perhaps this is causing a recursive loop)
![image](https://user-images.githubusercontent.com/11482252/89957678-0b8e2180-dc06-11ea-9ee2-0500985687ea.png)

This entire structure is a part of a nomadic structure, using the [nomad books mod](https://www.curseforge.com/minecraft/mc-mods/nomadbooks). The structure is taken mining and stuff, then re-deployed at the base camp where items are sucked out of the export 1 and export 2 bus and sent to the main base's sorting system. So, maybe the exposed extractors or filters could also cause a problem?
![image](https://user-images.githubusercontent.com/11482252/89957985-d1714f80-dc06-11ea-8719-515e11d7841e.png)

**Comment by JoshMayberry** [comment]
I just tried removing the spot where the output from the smelter array goes back into the main bus, and it still crashed with the same recursive loop.
[crash-2020-08-11_19.52.14-server.txt](https://github.com/cakewhip/ezpas/files/5059976/crash-2020-08-11_19.52.14-server.txt)

**Comment by cakewhip** [comment]
It is most likely an issue with the large number of filtered pipes. EZPaS treats items like water, as in the filtered pipe will apply its filter to all pipes coming afterward, like an actual pipe in real life. Because of that, EZPaS sees your rectangle of filtered pipes as a bunch of filters combining with each other, from the entry pipe to the last filtered pipe. This is a confusing aspect of EZPaS, and I will am planning on making a change to revert it back to its original form soon.

**Comment by cakewhip** [comment]
This may have been fixed as of v1.1.2. Test your world with that version (available for both 1.16.1 and 1.16.2) and comment back here so I can update the issue.

**Comment by JoshMayberry** [comment]
If I use version 1.1.2, I get the following error in the command window when the server starts up (no crash log was generated):
```
[main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'ezpas'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:32) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:125) [intermediary-server.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.lang.NoSuchMethodError: com.kqp.ezpas.network.SetPersistStateC2S.register()V
        at com.kqp.ezpas.init.Ezpas.onInitialize(Ezpas.java:81) ~[ezpas-1.1.2-1.16.1.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        ... 17 more
```

It loads fine on the client though.

**Comment by cakewhip** [comment]
Well that's a little embarrassing. I just finished up another release, also fixing the error in that crash report.

**Comment by JoshMayberry** [comment]
:) It is ok. You're doing amazing with this mod. We appreciate it and the work you put into it a lot.

**Comment by JoshMayberry** [comment]
Just tried loading version 1.2.0, and no server crash now. 🥇
